### ISSUE TITLE
About fp16 inference with NNAPI

### ISSUE THREAD

**Issue by jimmychiangmtk** [thstkdgus35/ntire-2020-deblur-mobile#1]
Hi,

There are `deblur_256.tflite` and `deblur_fp16_256.tflite` in the `models` directory.
Actually, you can use `--allow_fp16=1` in `benchmark_model` config to run fp16 inference with fp32 TFLite model.

If the participant want to run in fp16, do they need to provide real FP16 TFLite, or just using `--allow_fp16=1` is enough?

**Comment by sanghyun-son** [comment]
Hello.

Basically, we recommend a fully-optimized model for the final submission. In other words, it is desirable to submit an FP16 version if you would like to execute the model on the FP16 environment. However, we do not force any constraints for easier deployment. Therefore, it is also possible to submit the FP32 model and evaluate it with the `allow_fp16=1` option.

The most important thing is to describe your runtime arguments precisely in the factsheet so that we can reproduce your results.

Thank you!

**Comment by jimmychiangmtk** [comment]
> Hello.
> 
> Basically, we recommend a fully-optimized model for the final submission. In other words, it is desirable to submit an FP16 version if you would like to execute the model on the FP16 environment. However, we do not force any constraints for easier deployment. Therefore, it is also possible to submit the FP32 model and evaluate it with the `allow_fp16=1` option.
> 
> The most important thing is to describe your runtime arguments precisely in the factsheet so that we can reproduce your results.
> 
> Thank you!

Got it, thank you.
